### ISSUE TITLE
Docu is disorienting :)

### ISSUE THREAD

**Issue by davidhellmann** [Rias500/craft-schema#2]
This doesn't work:
```
          {# @var schema \Spatie\SchemaOrg\Schema #}
          {% set schema = craft.schema %}
          {{ schema
            .person
            .name("Rias Van der Veken")
            .email("hello@rias.be")
            .company(
              schema.localBusiness
              .name("Marbles")
              .address(schema.postalAddress
                .addressCountry("Belgium")
                .addressLocality("Antwerp")
                .addressRegion("Antwerp")
                .postalCode(2000)
                .streetAddress("IJzerenpoortkaai 3")
              )
            )
          }}
```

When I add `| raw` it's fine. Maybe you can update this. 
```

          {# @var schema \Spatie\SchemaOrg\Schema #}
          {% set schema = craft.schema %}
          {{ schema
            .person
            .name("Rias Van der Veken")
            .email("hello@rias.be")
            .company(
              schema.localBusiness
              .name("Marbles")
              .address(schema.postalAddress
                .addressCountry("Belgium")
                .addressLocality("Antwerp")
                .addressRegion("Antwerp")
                .postalCode(2000)
                .streetAddress("IJzerenpoortkaai 3")
              )
            ) | raw
          }}
```

**Comment by davidhellmann** [comment]
And is there a trick to use autocompletion? When I write every property in a own line it does not work.

**Comment by riasvdv** [comment]
I've updated the readme to include `| raw` that was a good point!

Autocompletion only works in PHPStorm with the Symfony plugin installed and activated, are you sure you have all these requirements?

**Comment by davidhellmann** [comment]
yes, it's all active. `schema.foo` works fine but when I try it like the format in the readme:

```
 schema
  .foo
  .bar
```

the autocomplete does not work.

**Comment by riasvdv** [comment]
Finally had time to look into this, seems like it's just a limitation of the twig autocompletion.

So this has full autocompletion:

`{{ schema.person.name }}` ✅ 

Only when you keep it on a single line. But if you want to add something else this doesn't autocomplete:

`{{ schema.person.name("Rias").em }}l` ❌ 

So what you can do is always start with your cursor from `person` again:

`{{ schema.person.<cursor here>.name("Rias") }}` ✅ 

This will bring up all the properties. Then afterwards you can clean up the the code with new lines.
